name: Deploy Frontend Challenge 2

on:
  push:
    branches: [master, main]
    paths:
      - "frontend_challenge_2/challenges/tsbs0514/**"
  pull_request:
    branches: [master, main]
    paths:
      - "frontend_challenge_2/challenges/tsbs0514/**"

permissions:
  contents: read
  pages: write # ← Pages へ書き込み
  id-token: write # ← OIDC デプロイ用

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: |
            frontend_challenge_2/challenges/tsbs0514/package-lock.json

      - name: Install dependencies
        working-directory: frontend_challenge_2/challenges/tsbs0514
        run: npm ci

      - name: Install Playwright browsers
        working-directory: frontend_challenge_2/challenges/tsbs0514
        run: npx playwright install --with-deps

      - name: Run unit tests
        working-directory: frontend_challenge_2/challenges/tsbs0514
        run: npm test

      - name: Run E2E tests
        working-directory: frontend_challenge_2/challenges/tsbs0514
        run: npm run test:e2e
        env:
          CI: true
        timeout-minutes: 10

      - name: Build & export Next.js
        working-directory: frontend_challenge_2/challenges/tsbs0514
        run: npm run build # next build → next export (output: export)

      # GitHub Pages 用アーティファクトをアップロード
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend_challenge_2/challenges/tsbs0514/out

  # ────────────────────────────────────────────────
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      # GitHub Pages を初期化
      - uses: actions/configure-pages@v4

      # アーティファクトをデプロイ
      - id: deploy
        uses: actions/deploy-pages@v4
